### ISSUE TITLE
Steam and Discord integrations don't work

### ISSUE THREAD

**Issue by OrigamingWasTaken** [coatlessali/UltraNix#17]
Hello, sorry If this is just a problem on my end.
I've moved the 2 files (`discord_game_sdk.dylib` and `libsteam_api64.dylib`) into the folder where my ultraport.sh script is.
I'm on MacOS, and the discord RPC and steam leaderboards aren't working.

**Comment by coatlessali** [comment]
It's possible the version of the Discord/Steam plugins have been updated. The only way to figure out what version the game needs, is to download each version 1 by 1, and then compare the md5sum of the 64-bit Windows dll with the one supplied by the game. Once you have the correct version narrowed down, just grab the MacOS files for that version.

Contributions are welcome if you figure it out.

**Comment by OrigamingWasTaken** [comment]
I just checked and it has not updated.
I found the `f3db5801dc9b75da671b39041e2e8bcf` md5 hash on the files which corresponds to 1.57

**Comment by coatlessali** [comment]
Awesome, glad you figured it out. I'll close it once the guide is updated.

**Comment by OrigamingWasTaken** [comment]
I cannot make pull requests for the wiki so I have cloned it. Here's the link to the modified markdown file: https://github.com/OrigamingWasTaken/UltraNix.Wiki/blob/master/Running-the-Ultraport-Script.md

**Comment by coatlessali** [comment]
Just remembered this exists, unfortunately that's a 404
