### ISSUE TITLE
Aborted (Core dumped)

### ISSUE THREAD

**Issue by UdontKnowMe69** [coatlessali/UltraNix#5]
I am a Deb linux user
So i have Ultrakill installed and it runs as well. I tried running it on WINE and it ran very choppy. So i came across this project. I followed the install instructions correctly as well. It doesnt run using the Steam cmd so i tried running it directly using:
   ./ULTRAKILL.x86_64
But terminal shows me the following error:
   Aborted (core dumped)
What is the issue why am i encountering this error and how do i fix this?

**Comment by coatlessali** [comment]
It is a known bug that the game will just refuse to launch sometimes, even multiple times in a row before finally launching. This becomes more frequent if you preload SDL for Wayland support. You could also try running through Steam Flatpak.

I'm looking into why this happens, as it seems wholly inconsistent.

**Comment by UdontKnowMe69** [comment]
![image](https://github.com/coatlessali/UltraNix/assets/110294290/beb34b52-11e6-454d-8025-2d5f10fef774)

**Comment by UdontKnowMe69** [comment]
Also i cant seem to be able to install even flatpak steam cause i tried it from both flathub and by downloading the .flatpak file and in both cases i recieve the error that my installed flatpak ver. is old. So i tried using the ppa of flatpak and it says "IP not found" for some reason so i cant install the flatpak version. Any other suggestions?

**Comment by UdontKnowMe69** [comment]
idk i seem to have the latest distro cause i use a chromebook and it doesnt show anymore updates

**Comment by coatlessali** [comment]
What does `cat /etc/os-release` say?

**Comment by UdontKnowMe69** [comment]
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by coatlessali** [comment]
You need to upgrade to Debian 12. Debian 11 has a very outdated version of Flatpak.

I don't support Chromebooks currently due to the finess required to make them play nicely, but let me know how it goes.

**Comment by UdontKnowMe69** [comment]
how do i update it using a deb repo? I tried it with WINE and it worked. Is there something similar for updating the flatpak pkg too?

**Comment by coatlessali** [comment]
Closing as wontfix, as I have no way of debugging this.
