### ISSUE TITLE
zsh: permission denied: ./ULTRAKILL.app

### ISSUE THREAD

**Issue by BDMCGaming** [coatlessali/UltraNix#6]
I ran the script directly as my user, and I'm getting this error. I've tried chmod to make it executable. Get Info says it belongs to me. So why can't I run it?
Uname output: Darwin itsawildmacbook.local 23.1.0 Darwin Kernel Version 23.1.0: Tue Sep 26 22:11:17 PDT 2023; root:xnu-10002.40.89.501.1~3/RELEASE_ARM64_T8103 arm64
Model: MacBookPro17,1

**Comment by coatlessali** [comment]
You may need to right click -> open ULTRAKILL.app for it to function. I don't work with MacOS very often.

**Comment by BDMCGaming** [comment]
I did try that. Also, I got the Unity logs from console
Mono path[0] = '/Applications/ULTRAKILL.app/Contents/Resources/Data/Managed'
Mono config path = '/Applications/ULTRAKILL.app/Contents/MonoBleedingEdge/etc'
Invalid serialized file version. File: "/Applications/ULTRAKILL.app/Contents/Resources/Data/globalgamemanagers". Expected version: 2019.4.40f1. Actual version: 2019.4.16f1. 
(Filename:  Line: 1608)

Unknown error occurred while loading '/Applications/ULTRAKILL.app/Contents/Resources/Data/globalgamemanagers'. 
(Filename:  Line: 209)

```
PlayerInitEngineNoGraphics settings: Failed to load PlayerSettings (internal index #0).
Most likely data file is corrupted, or built with mismatching
editor and platform support versions.
Failed to initialize engine
```

**Comment by BDMCGaming** [comment]
These logs specifically show up when doing `open --arch x86_64 ULTRAKILL.app`

**Comment by coatlessali** [comment]
Make sure you have Rosetta installed if it's an M1. Also be sure to try reinstalling the game. That file supposedly contains information on what renderers the game supports. I have no idea if Apple finally deprecated OpenGL or something, but that could be an issue.

**Comment by BDMCGaming** [comment]
Will try that when I get the chance.

**Comment by coatlessali** [comment]
> ```
> PlayerInitEngineNoGraphics settings: Failed to load PlayerSettings (internal index #0).
> Most likely data file is corrupted, or built with mismatching
> editor and platform support versions.
> Failed to initialize engine
> ```

Either something is corrupted or there's a mismatch of some kind in that file. I'll investigate later when I can.

**Comment by BDMCGaming** [comment]
i got it working. needed to redo it

**Comment by coatlessali** [comment]
Closing.
