### ISSUE TITLE
I know it's a known issue but I'm still curious if you've figured out why scrolling is so slow on Linux.

### ISSUE THREAD

**Issue by daemonspudguy** [coatlessali/UltraNix#8]

**Comment by coatlessali** [comment]
No idea. If I had to guess, it comes down to Unity using SDL2 for inputs on MacOS/Linux, and differences in how the two operate. I feel like whatever it is, it's probably also related to the dreaded mousebug.

**Comment by coatlessali** [comment]
Closing in favor of #9 being the main place for discussion.
